//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVWAREHOUSE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int id { get; set; }
        public int CongSuat { get; set; }
        public string opt { get; set; }
        public string MaQR { get; set; }
        public string TenSeries { get; set; }
    }
}
