//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVWAREHOUSE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class invwarehouseEntities : DbContext
    {
        public invwarehouseEntities()
            : base("name=invwarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietSanPham> ChiTietSanPhams { get; set; }
        public virtual DbSet<DanhMucSanPham> DanhMucSanPhams { get; set; }
        public virtual DbSet<TaiKhoanDangNhap> TaiKhoanDangNhaps { get; set; }
        public virtual DbSet<ThongTinTaiKhoan> ThongTinTaiKhoans { get; set; }
        public virtual DbSet<ThongTinHoaDon> ThongTinHoaDons { get; set; }
    
        public virtual int Usp_AddAccount(string usr, string pwd, string acc)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var accParameter = acc != null ?
                new ObjectParameter("acc", acc) :
                new ObjectParameter("acc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_AddAccount", usrParameter, pwdParameter, accParameter);
        }
    
        public virtual int Usp_ChangePassword(string usr, string pwd)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_ChangePassword", usrParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Usp_CheckAccountExist_Result> Usp_CheckAccountExist(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_CheckAccountExist_Result>("Usp_CheckAccountExist", usrParameter);
        }
    
        public virtual int Usp_DeleteAccount(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_DeleteAccount", usrParameter);
        }
    
        public virtual ObjectResult<Usp_LoadDanhSachTaiKhoan_Result> Usp_LoadDanhSachTaiKhoan(string acc)
        {
            var accParameter = acc != null ?
                new ObjectParameter("acc", acc) :
                new ObjectParameter("acc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_LoadDanhSachTaiKhoan_Result>("Usp_LoadDanhSachTaiKhoan", accParameter);
        }
    
        public virtual ObjectResult<Usp_Login_Result> Usp_Login(string usr, string pwd)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_Login_Result>("Usp_Login", usrParameter, pwdParameter);
        }
    
        public virtual int Usp_UpdateThongTin(string ten, Nullable<int> tuoi, string dc, string sDT, Nullable<int> id)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tuoiParameter = tuoi.HasValue ?
                new ObjectParameter("tuoi", tuoi) :
                new ObjectParameter("tuoi", typeof(int));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usp_UpdateThongTin", tenParameter, tuoiParameter, dcParameter, sDTParameter, idParameter);
        }
    }
}
